[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:keepalive]
command=tail -f /dev/null
autostart=true
autorestart=true

# [program:node-app]
# command=node index.js
# autostart=true
# autorestart=true
# stderr_logfile=/dev/stderr
# stdout_logfile=/dev/stdout

# [program:worker]
# command=node worker.js
# autostart=true
# autorestart=true
# stderr_logfile=/dev/stderr
# stdout_logfile=/dev/stdout